import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import HeroPage from "./hero/page";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight : ['300' , '400' , '700' , '500'],
  display : 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/aesthetic-moment" rel="stylesheet"></link>
      </head>
      <body
        className={`${poppins.variable} antialiased`}
      >
        <HeroPage/>
        {children}
      </body>
    </html>
  );
}
